#!/usr/bin/env python3
"""Convert WAV files to C header arrays for M5Stick firmware.

Resamples to 16kHz mono 16-bit PCM and writes a complete WAV file
(including RIFF header) as a PROGMEM byte array.

Usage: python3 wav2h.py output.h label1=file1.wav label2=file2.wav ...
"""
import sys
import struct
import io
import wave

def resample_to_mono_16k(wav_path):
    with wave.open(wav_path, 'rb') as wf:
        n_channels = wf.getnchannels()
        samp_width = wf.getsampwidth()
        frame_rate = wf.getframerate()
        raw = wf.readframes(wf.getnframes())

    # Convert to list of int16 samples
    if samp_width == 2:
        fmt = '<' + 'h' * (len(raw) // 2)
        samples = list(struct.unpack(fmt, raw))
    else:
        samples = list(raw)

    # Downmix to mono if stereo
    if n_channels == 2:
        mono = []
        for i in range(0, len(samples), 2):
            mono.append((samples[i] + samples[i + 1]) // 2)
        samples = mono

    # Resample to 16kHz using simple linear interpolation
    target_rate = 16000
    if frame_rate != target_rate:
        ratio = target_rate / frame_rate
        out = []
        for i in range(int(len(samples) * ratio)):
            src_idx = i / ratio
            idx = int(src_idx)
            frac = src_idx - idx
            if idx + 1 < len(samples):
                val = int(samples[idx] * (1 - frac) + samples[idx + 1] * frac)
            else:
                val = samples[idx]
            out.append(max(-32768, min(32767, val)))
        samples = out

    # Re-encode as complete WAV (with RIFF header)
    buf = io.BytesIO()
    with wave.open(buf, 'wb') as wf_out:
        wf_out.setnchannels(1)
        wf_out.setsampwidth(2)
        wf_out.setframerate(target_rate)
        wf_out.writeframes(struct.pack('<' + 'h' * len(samples), *samples))
    return buf.getvalue()


def main():
    if len(sys.argv) < 4:
        print(__doc__.strip())
        sys.exit(1)

    output_path = sys.argv[1]
    pairs = sys.argv[2:]

    labels = []
    for p in pairs:
        if '=' not in p:
            print(f"Expected label=file.wav, got: {p}")
            sys.exit(1)
        labels.append(p.split('=', 1))

    lines = []
    lines.append("// Auto-generated by wav2h.py — do not edit\n")
    lines.append("#pragma once")
    lines.append('#include <stdint.h>\n')

    for label, wav_path in labels:
        print(f"Processing {wav_path} -> {label} ...")
        data = resample_to_mono_16k(wav_path)
        macro = label.upper()
        lines.append(f"#define {macro}_LEN {len(data)}")
        lines.append(f"extern const uint8_t {label}[{macro}_LEN];\n")

    for label, wav_path in labels:
        data = resample_to_mono_16k(wav_path)
        macro = label.upper()
        lines.append(f"const uint8_t {label}[{macro}_LEN] PROGMEM = {{")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            lines.append("  " + ", ".join(str(b) for b in chunk) + ",")
        lines.append("};\n")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    total = sum(len(resample_to_mono_16k(w)) for _, w in labels)
    print(f"Wrote {output_path} ({total} bytes)")


if __name__ == "__main__":
    main()
